### ISSUE TITLE
Sass compiler periodically stops working until I restart Visual Studio

### ISSUE THREAD

**Issue by ByteBlast** [madskristensen/WebEssentials2013#1728]
The Sass compiler frequently breaks for no good reason and I have to restart Visual Studio to get the compiler to work again.

I could change a Sass property and the CSS output will never update. If I delete all of the Sass and save the document - the CSS output does change - it should technically be empty but when the compiler breaks it remains the same.

I tried using the menu item to "recompile all Sass" but to no avail.

I can only get my Sass to compile if I restart Visual Studio. This happens about once every 30 minutes or once every 20 saves, something frequent like that.

**Comment by mysticman** [comment]
Yes i have a same problem under VS2013 Premium, but every time when I try to compile a syntax error a a wrong SCSS. When I fix the Issue, nothing happens just get the same error messages, untill the VS restart.

Err msg: compilation failed: The service failed to respond to this request.

Just the Visual Studio restart help very annoying.

**Comment by am11** [comment]
Guys when this happens and the VS is still running, can you try checking Task Manager if node.js is listed there (the entry under Processes is `Evented I/O for V8 JavaScript (32 bit)`. If it is, try to kill that process (or even all process with the name) and save again.

This is not the permanent fix but just a workaround. Note that with vNext of [node-sass](https://github.com/sass/node-sass/) things are drastically changed, so hopefully it will be fixed if node-sass package was the culprit.

(Also, you may want to try switching the engine to Ruby-Sass, since WE now supports both runtimes for Sass compilation)

**Comment by ByteBlast** [comment]
I had not used Visual Studio for Sass again until today so apoligies for the delay. I _just_ encountered the same problem and immediately checked the Task Manaager - `Evented I/O for V8 JavaScript (32 bit)` was not listed there. I restarted Visual Studio and hey presto, `Evented I/O for V8 JavaScript (32 bit)` is listed and now my Sass compiles.

**Comment by ssimontis** [comment]
I just experienced a similar issue with the LESS compiler. I had a LESS file in Bootstrap that could not be compiled individually (works fine when compiling Bootstrap.less). I received several errors regarding missing variables that would not go away. I even removed the file from VS and was still receiving errors from the non-existent file! Restarting fixed everything, but I will check the Task Manager for that Node task next time.

**Comment by Carlosxell** [comment]
Man, thanks!!!! I have 1 day lost looking for this solution!

**Comment by am11** [comment]
I face this issue almost everyday at work when compiling Less. So I have a script handy.

`stop-node.ps1` on desktop with following code:

```powershell
stop-process -name node
```

Whenever it stops working, double click and get it working without restarting VS.

**Comment by marymusker** [comment]
I had this issue this morning. I realise this thread is 18 months old but in case it helps anyone.... I discovered I had a single stray "}" in one of my SCSS files, and that was stopping everything compiling. I deleted the } and all back to normal.

**Comment by daudi13** [comment]
i have been having this issues for months now I have never found a solution for it. I've tried googling for solutions but I haven't been successful. i really need help
